<?php


namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    const DATA = [
        "admin.login",
        "admin.login.data",
        "admin.forgot.password",
        "admin.forgot.password.data",
        "admin.reset.password",
        "admin.reset.password.data",
        "admin.logout",
        "dashboard",
        "manage.users",
        "user.add",
        "user.add.data",
        "user.update",
        "user.change.status",
        "user.update.data",
        "user.detail",
        "user.delete",
        "role.access",
        "role.add",
        "role.edit",
        "role.delete",
        "role.status.update",
        "role.detail",
        "user.gallery.access",
        "user.gallery.status.update",
        "user.gallery.add",
        "user.gallery.edit",
        "user.gallery.detail",
        "user.gallery.delete",
        "color.access",
        "color.status.update",
        "color.add",
        "color.edit",
        "color.detail",
        "color.delete",
        "calendar.access",
        "calendar.add",
        "calendar.edit",
        "calendar.detail",
        "calendar.delete",
        "series.access",
        "series.add",
        "series.edit",
        "series.detail",
        "series.status.update",
        "series.delete",
        "book.access",
        "book.add",
        "book.edit",
        "book.detail",
        "book.status.update",
        "book.delete",
        "premise.access",
        "premise.add",
        "premise.edit",
        "premise.detail",
        "premise.status.update",
        "premise.delete",
        "outline.access",
        "outline.add",
        "outline.edit",
        "outline.detail",
        "outline.status.update",
        "outline.delete",
        "chapter.access",
        "chapter.add",
        "chapter.edit",
        "chapter.detail",
        "chapter.status.update",
        "chapter.delete",
        "card.access",
        "card.add",
        "card.edit",
        "card.detail",
        "card.status.update",
        "card.delete",
        "timeline.access",
        "timeline.add",
        "timeline.edit",
        "timeline.detail",
        "timeline.status.update",
        "timeline.delete",
        "timeline.event.type.access",
        "timeline.event.type.add",
        "timeline.event.type.edit",
        "timeline.event.type.detail",
        "timeline.event.type.status.update",
        "timeline.event.type.delete",
        "planner.access",
        "planner.add",
        "planner.edit",
        "planner.detail",
        "planner.status.update",
        "planner.delete",
        "group.access",
        "group.add",
        "group.edit",
        "group.detail",
        "group.status.update",
        "group.delete",
    ];

    public function run(){
        foreach (self::DATA as $val) {
            permission::create(['name' => $val]);
        }
    }
}
